matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode8
      sudo: required

script:
  - echo ">> Building and testing Swift SDK for DB2 CLI."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.travis/osx.sh; fi
  - echo ">> Swift SDK for DB2 CLI built and tested. Check above for status."

language: cpp

notifications:
  slack: ibm-analytics:LgaBAvT7hSn8vGXR4elXTfW1
